name: Publish Extension

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Package extension
        run: npm run package
        
      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Create VSIX package
        run: npx vsce package
        
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloud-ai-yingcai-${{ steps.package-version.outputs.current-version }}.vsix
          path: "*.vsix"
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: cloud-ai-yingcai-${{ steps.package-version.outputs.current-version }}.vsix
          
      - name: Publish to Visual Studio Marketplace
        run: |
          npx vsce publish -p ${{ secrets.VSCE_PAT }} --packagePath *.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }} 